index_parent:
    path: /IndexParent
    defaults:
        _controller: 'ezsolr.controller.workshop:indexParentAction'

is_empty_field:
    path: /IsFieldEmpty
    defaults:
        _controller: 'ezsolr.controller.workshop:isEmptyFieldAction'

index_children:
    path: /IndexChildren
    defaults:
        _controller: 'ezsolr.controller.workshop:indexChildrenAction'

location_query_criterion:
    path: /LocationQueryCriterion
    defaults:
        _controller: 'ezsolr.controller.workshop:locationQueryCriterionAction'

better_fulltext:
    path: /BetterFulltext
    defaults:
        _controller: 'ezsolr.controller.workshop:betterFulltextAction'

more_like_this:
    path: /MoreLikeThis
    defaults:
        _controller: 'ezsolr.controller.workshop:moreLikeThisAction'

custom_field_facet:
    path: /CustomFieldFacet
    defaults:
        _controller: 'ezsolr.controller.workshop:customFieldFacetAction'
