imports:
     - {resource: query_translator.yml}

parameters:
    ezpublish.persistence.field_type_registry.class: EzSolrWorkshopBundle\Core\Persistence\FieldTypeRegistry
    ezpublish.search.common.field_name_generator.map:
        ez_integer: 'i'
        ez_minteger: 'mi'
        ez_id: 'id'
        ez_mid: 'mid'
        ez_string: 's'
        ez_mstring: 'ms'
        ez_long: 'l'
        ez_text: 't'
        ez_html: 'h'
        ez_boolean: 'b'
        ez_mboolean: 'mb'
        ez_float: 'f'
        ez_double: 'd'
        ez_date: 'dt'
        ez_point: 'p'
        ez_currency: 'c'
        ez_geolocation: 'gl'
        ez_document: 'doc'
        ez_fulltext: 'fulltext'
        ez_case_sensitive_string: 'css'
    ezpublish.fieldType.indexable.ezstring.class: EzSolrWorkshopBundle\Core\FieldType\TextLine\SearchField

services:
    ezsolr.controller.workshop:
        class: EzSolrWorkshopBundle\Controller\WorkshopController
        arguments:
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content_type'
        calls:
            - [setContainer, ['@service_container']]

    search.field_mapper.content_translation.project_parent:
        class: EzSolrWorkshopBundle\Core\FieldMapper\ContentTranslation\ProjectParentFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_handler'
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content_translation}

    search.field_mapper.content.is_field_empty:
        class: EzSolrWorkshopBundle\Core\FieldMapper\Content\IsFieldEmptyFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@ezpublish.search.common.field_name_generator'
            - '@ezpublish.persistence.field_type_registry'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content}

    search.criterion_visitor.is_field_empty:
        class: EzSolrWorkshopBundle\Core\CriterionVisitor\IsFieldEmpty
        arguments:
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@ezpublish.search.common.field_name_generator'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    search.field_mapper.content_translation.blog_children:
        class: EzSolrWorkshopBundle\Core\FieldMapper\ContentTranslation\BlogChildrenFieldMapper
        arguments:
            - '@search.repository.filter_service'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content_translation}

    search.inner_repository:
        class: '%ezpublish.api.inner_repository.class%'
        factory:
            - '@ezpublish.api.repository.factory'
            - buildRepository
        arguments:
            - '@ezpublish.api.persistence_handler'
            - '@ezpublish.spi.search.legacy'
        lazy: true
        public: false

    search.repository.filter_service:
        class: '%ezpublish.api.service.search.class%'
        factory:
            - '@search.inner_repository'
            - getSearchService
        lazy: true
        public: false

    search.criterion_visitor.location_query:
        class: EzSolrWorkshopBundle\Core\CriterionVisitor\LocationQuery
        arguments:
            - '@ezpublish.search.solr.query.location.criterion_visitor.aggregate'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}

    search.criterion_visitor.more_like_this:
        class: EzSolrWorkshopBundle\Core\CriterionVisitor\MoreLikeThis
        arguments:
            - '@ezpublish.search.solr.document_mapper'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    search.facet_builder_visitor.custom_field:
        class: EzSolrWorkshopBundle\Core\FacetBuilderVisitor\CustomFieldFacetBuilderVisitor
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}

    search.facet_builder_visitor.field_prefix:
        class: EzSolrWorkshopBundle\Core\FacetBuilderVisitor\FieldPrefixFacetBuilderVisitor
        tags:
            - {name: ezpublish.search.solr.query.content.facet_builder_visitor}
            - {name: ezpublish.search.solr.query.location.facet_builder_visitor}
