parameters:
    ezpublish.persistence.field_type_registry.class: EzSolrWorkshopBundle\Core\Persistence\FieldTypeRegistry

services:
    ezsolr.controller.workshop:
        class: EzSolrWorkshopBundle\Controller\WorkshopController
        arguments:
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content_type'
        calls:
            - [setContainer, ['@service_container']]

    search.field_mapper.content_translation.project_parent:
        class: EzSolrWorkshopBundle\Core\FieldMapper\ContentTranslation\ProjectParentFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_handler'
            - '@ezpublish.spi.persistence.location_handler'
            - '@ezpublish.spi.persistence.content_type_handler'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content_translation}

    search.field_mapper.content.is_field_empty:
        class: EzSolrWorkshopBundle\Core\FieldMapper\Content\IsFieldEmptyFieldMapper
        arguments:
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@ezpublish.search.common.field_name_generator'
            - '@ezpublish.persistence.field_type_registry'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content}

    search.criterion_visitor.is_field_empty:
        class: EzSolrWorkshopBundle\Core\CriterionVisitor\IsFieldEmpty
        arguments:
            - '@ezpublish.spi.persistence.content_type_handler'
            - '@ezpublish.search.common.field_name_generator'
        tags:
            - {name: ezpublish.search.solr.query.content.criterion_visitor}
            - {name: ezpublish.search.solr.query.location.criterion_visitor}

    search.field_mapper.content_translation.blog_children:
        class: EzSolrWorkshopBundle\Core\FieldMapper\ContentTranslation\BlogChildrenFieldMapper
        arguments:
            - '@search.repository.filter_service'
        tags:
            - {name: ezpublish.search.solr.field_mapper.content_translation}

    search.inner_repository:
        class: '%ezpublish.api.inner_repository.class%'
        factory:
            - '@ezpublish.api.repository.factory'
            - buildRepository
        arguments:
            - '@ezpublish.api.persistence_handler'
            - '@ezpublish.spi.search.legacy'
        lazy: true
        public: false

    search.repository.filter_service:
        class: '%ezpublish.api.service.search.class%'
        factory:
            - '@search.inner_repository'
            - getSearchService
        lazy: true
        public: false
